### ISSUE TITLE
feat: add query language for filtering / coloring points in umap

### ISSUE THREAD

**Issue by twitwi** [sound-scape-explorer/sound-scape-explorer#2]
(some random notes)

For now, probably a lucene-query-parser + custom execution...

- the myna grammar is not complete (not sure the peg one is)
- none handles AND OR priority

### Object store query languages

https://stackoverflow.com/questions/28619342/is-there-any-rest-api-query-standard-dsl-to-express-complex-filters-in-get-url

https://olingo.apache.org/doc/javascript/index.html (all broken)

### Using lucene/elastic/opensearch

The lucene query syntax might be a good direction, or the Kibana query language.
The fully open fork is OpenSearch https://opensearch.org/

- https://opensearch.org/docs/latest/opensearch/query-dsl/index/

Some js stuff...

- https://www.npmjs.com/package/lucene-query-parser
- https://www.npmjs.com/package/lucene-queryparser (same it seems)
- or myna https://stackoverflow.com/questions/5269545/how-to-build-a-parser-to-parse-lucene-syntax-to-an-ast

**Comment by bamdadfr** [comment]
closing stale issue
